name: Phoebus build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup Maven and Java Action
      uses: s4u/setup-maven-action@v1.18.0
      with:
        java-version: '17'
        maven-version: '3.9.6'

    - name: Checkout Phoebus
      shell: bash
      run: |
        mkdir -p "${GITHUB_WORKSPACE}/lib"
        git clone --branch v5.0.4 --single-branch https://github.com/ControlSystemStudio/phoebus "${GITHUB_WORKSPACE}/lib/phoebus"

    - name: Build and install Phoebus dependencies
      working-directory: ${{ github.workspace }}/lib/phoebus
      run: mvn --batch-mode clean install -DskipTests=true

    - name: Build EIC Phoebus
      run: mvn --batch-mode clean install -DskipTests=true -Ddocs=${{ github.workspace }}/lib/phoebus/docs

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: eic-phoebus-${{ matrix.os }}
        path: |
          ${{ github.workspace }}/target/*.jar
          ${{ github.workspace }}/target/eic-phoebus-*.zip
          ${{ github.workspace }}/target/eic-phoebus-*.tar.gz

